<?php

namespace Database\Seeders;

use App\Models\Barangay;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

/**
 * All 315 barangays of Catanduanes (11 municipalities), per the 2020 PSGC
 * list. Many barangay names repeat across municipalities (e.g. "San Roque",
 * "Salvacion"), so `code` is built from municipality + barangay to stay
 * unique, e.g. "virac-san-roque".
 */
class BarangaySeeder extends Seeder
{
    public const BARANGAYS = [
        'Bagamanoc' => [
            'Antipolo',
            'Bacak',
            'Bagatabao',
            'Bugao',
            'Cahan',
            'Hinipaan',
            'Magsaysay',
            'Poblacion',
            'Quezon',
            'Quigaray',
            'Sagrada',
            'Salvacion',
            'San Isidro',
            'San Rafael',
            'San Vicente',
            'Santa Mesa',
            'Santa Teresa',
            'Suchan',
        ],
        'Baras' => [
            'Abihao',
            'Agban',
            'Bagong Sirang',
            'Batolinao',
            'Benticayan',
            'Buenavista',
            'Caragumihan',
            'Danao',
            'Eastern Poblacion',
            'Ginitligan',
            'Guinsaanan',
            'J. M. Alberto',
            'Macutal',
            'Moning',
            'Nagbarorong',
            'Osmeña',
            'P. Teston',
            'Paniquihan',
            'Puraran',
            'Putsan',
            'Quezon',
            'Rizal',
            'Sagrada',
            'Salvacion',
            'San Lorenzo',
            'San Miguel',
            'Santa Maria',
            'Tilod',
            'Western Poblacion',
        ],
        'Bato' => [
            'Aroyao Pequeño',
            'Bagumbayan',
            'Banawang',
            'Batalay',
            'Binanuahan',
            'Bote',
            'Buenavista',
            'Cabugao',
            'Cagraray',
            'Carorian',
            'Guinobatan',
            'Ilawod',
            'Libjo',
            'Libod Poblacion',
            'Marinawa',
            'Mintay',
            'Oguis',
            'Pananaogan',
            'San Andres',
            'San Pedro',
            'San Roque',
            'Santa Isabel',
            'Sibacungan',
            'Sipi',
            'Talisay',
            'Tamburan',
            'Tilis',
        ],
        'Caramoran' => [
            'Baybay',
            'Bocon',
            'Bothoan',
            'Buenavista',
            'Bulalacao',
            'Camburo',
            'Dariao',
            'Datag East',
            'Datag West',
            'Guiamlong',
            'Hitoma',
            'Icanbato',
            'Inalmasinan',
            'Iyao',
            'Mabini',
            'Maui',
            'Maysuran',
            'Milaviga',
            'Obi',
            'Panique',
            'Sabangan',
            'Sabloyon',
            'Salvacion',
            'Supang',
            'Toytoy',
            'Tubli',
            'Tucao',
        ],
        'Gigmoto' => [
            'Biong',
            'Dororian',
            'Poblacion District I',
            'Poblacion District II',
            'Poblacion District III',
            'San Pedro',
            'San Vicente',
            'Sicmil',
            'Sioron',
        ],
        'Pandan' => [
            'Bagawang',
            'Balagñonan',
            'Baldoc',
            'Canlubi',
            'Catamban',
            'Cobo',
            'Hiyop',
            'Libod',
            'Lourdes',
            'Lumabao',
            'Marambong',
            'Napo',
            'Oga',
            'Pandan del Norte',
            'Pandan del Sur',
            'Panuto',
            'Porot',
            'Salvacion',
            'San Andres',
            'San Isidro',
            'San Rafael',
            'San Roque',
            'Santa Cruz',
            'Tabugoc',
            'Tokio',
            'Wagdas',
        ],
        'Panganiban' => [
            'Alinawan',
            'Babaguan',
            'Bagong Bayan',
            'Burabod',
            'Cabuyoan',
            'Cagdarao',
            'Mabini',
            'Maculiw',
            'Panay',
            'Salvacion',
            'San Antonio',
            'San Joaquin',
            'San Jose',
            'San Juan',
            'San Miguel',
            'San Nicolas',
            'San Pedro',
            'San Vicente',
            'Santa Ana',
            'Santa Maria',
            'Santo Santiago',
            'Taopon',
            'Tibo',
        ],
        'San Andres' => [
            'Agojo',
            'Alibuag',
            'Asgad',
            'Bagong Sirang',
            'Barihay',
            'Batong Paloway',
            'Belmonte',
            'Bislig',
            'Bon-ot',
            'Cabcab',
            'Cabungahan',
            'Carangag',
            'Catagbacan',
            'Codon',
            'Comagaycay',
            'Datag',
            'Divino Rostro',
            'Esperanza',
            'Hilawan',
            'Lictin',
            'Lubas',
            'Manambrag',
            'Mayngaway',
            'Palawig',
            'Puting Baybay',
            'Rizal',
            'Salvacion',
            'San Isidro',
            'San Jose',
            'San Roque',
            'San Vicente',
            'Santa Cruz',
            'Sapang Palay',
            'Tibang',
            'Timbaan',
            'Tominawog',
            'Wagdas',
            'Yocti',
        ],
        'San Miguel' => [
            'Atsan',
            'Balatohan',
            'Boton',
            'Buhi',
            'Dayawa',
            'J. M. Alberto',
            'Katipunan',
            'Kilikilihan',
            'Mabato',
            'Obo',
            'Pacogon',
            'Pagsangahan',
            'Pangilao',
            'Paraiso',
            'Poblacion District II',
            'Poblacion District III',
            'Progreso',
            'Salvacion',
            'San Juan',
            'San Marcos',
            'Santa Elena',
            'Siay',
            'Solong',
            'Tobrehon',
        ],
        'Viga' => [
            'Almojuela',
            'Ananong',
            'Asuncion',
            'Batohonan',
            'Begonia',
            'Botinagan',
            'Buenavista',
            'Burgos',
            'Del Pilar',
            'Mabini',
            'Magsaysay',
            'Ogbong',
            'Osmeña',
            'Pedro Vera',
            'Peñafrancia',
            'Quezon',
            'Quirino',
            'Rizal',
            'Roxas',
            'Sagrada',
            'San Isidro',
            'San Jose Oco',
            'San Jose Poblacion',
            'San Pedro',
            'San Roque',
            'San Vicente',
            'Santa Rosa',
            'Soboc',
            'Tambongon',
            'Tinago',
            'Villa Aurora',
        ],
        'Virac' => [
            'Antipolo del Norte',
            'Antipolo del Sur',
            'Balite',
            'Batag',
            'Bigaa',
            'Buenavista',
            'Buyo',
            'Cabihian',
            'Calabnigan',
            'Calampong',
            'Calatagan Proper',
            'Calatagan Tibang',
            'Capilihan',
            'Casoocan',
            'Cavinitan',
            'Concepcion',
            'Constantino',
            'Danicop',
            'Dugui San Isidro',
            'Dugui San Vicente',
            'Dugui Too',
            'F. Tacorda Village',
            'Francia',
            'Gogon Centro',
            'Gogon Sirangan',
            'Hawan Grande',
            'Hawan Ilaya',
            'Hicming',
            'Ibong Sapa',
            'Igang',
            'Juan M. Alberto',
            'Lanao',
            'Magnesia del Norte',
            'Magnesia del Sur',
            'Marcelo Alberto',
            'Marilima',
            'Pajo Baguio',
            'Pajo San Isidro',
            'Palnab del Norte',
            'Palnab del Sur',
            'Palta Big',
            'Palta Salvacion',
            'Palta Small',
            'Rawis',
            'Salvacion',
            'San Isidro Village',
            'San Jose',
            'San Juan',
            'San Pablo',
            'San Pedro',
            'San Roque',
            'San Vicente',
            'Santa Cruz',
            'Santa Elena',
            'Santo Cristo',
            'Santo Domingo',
            'Santo Niño',
            'Simamla',
            'Sogod-Simamla',
            'Sogod-Tibgao',
            'Talisoy',
            'Tubaon',
            'Valencia',
        ],
    ];

    public function run(): void
    {
        foreach (self::BARANGAYS as $municipality => $names) {
            foreach ($names as $name) {
                Barangay::firstOrCreate(
                    ['code' => Str::slug($name)],
                    ['name' => $name],
                );
            }
        }
    }
}